export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export type Database = {
  public: {
    Tables: {
      agencies: { Row: { id: string; slug: string; name: string; description: string | null; phone: string | null; email: string | null; website: string | null; logo_path: string | null; created_at: string }; Insert: { id?: string; slug: string; name: string; description?: string | null; phone?: string | null; email?: string | null; website?: string | null; logo_path?: string | null; created_at?: string }; Update: Partial<Database['public']['Tables']['agencies']['Insert']> }
      agents: { Row: { id: string; agency_id: string | null; slug: string; bio: string | null; phone: string | null; email: string | null; avatar_path: string | null; access_blocked: boolean; created_at: string }; Insert: { id: string; agency_id?: string | null; slug: string; bio?: string | null; phone?: string | null; email?: string | null; avatar_path?: string | null; access_blocked?: boolean; created_at?: string }; Update: Partial<Database['public']['Tables']['agents']['Insert']> }
      site_settings: { Row: { key: string; value: Json; updated_at: string }; Insert: { key: string; value?: Json; updated_at?: string }; Update: Partial<Database['public']['Tables']['site_settings']['Insert']> }
      properties: { Row: { id: string; slug: string; title: string; description: string | null; city: string; neighborhood: string | null; property_type: string; transaction_type: string; price: number; bedrooms: number; bathrooms: number; area_m2: number; features: string[]; cover_path: string | null; status: string; agency_id: string | null; agent_id: string | null; created_at: string; updated_at: string }; Insert: { id?: string; slug: string; title: string; description?: string | null; city: string; neighborhood?: string | null; property_type: string; transaction_type: string; price: number; bedrooms?: number; bathrooms?: number; area_m2?: number; features?: string[]; cover_path?: string | null; status?: string; agency_id?: string | null; agent_id?: string | null; created_at?: string; updated_at?: string }; Update: Partial<Database['public']['Tables']['properties']['Insert']> }
      property_images: { Row: { id: string; property_id: string; path: string; alt: string | null; sort_order: number; created_at: string }; Insert: { id?: string; property_id: string; path: string; alt?: string | null; sort_order?: number; created_at?: string }; Update: Partial<Database['public']['Tables']['property_images']['Insert']> }
      favorites: { Row: { user_id: string; property_id: string; created_at: string }; Insert: { user_id: string; property_id: string; created_at?: string }; Update: never }
      inquiries: { Row: { id: string; user_id: string | null; property_id: string | null; name: string; email: string; phone: string | null; message: string; status: string; created_at: string }; Insert: { id?: string; user_id?: string | null; property_id?: string | null; name: string; email: string; phone?: string | null; message: string; status?: string; created_at?: string }; Update: Partial<Database['public']['Tables']['inquiries']['Insert']> }
      viewing_requests: { Row: { id: string; user_id: string | null; property_id: string; name: string; email: string; phone: string | null; requested_date: string | null; message: string | null; status: string; created_at: string }; Insert: { id?: string; user_id?: string | null; property_id: string; name: string; email: string; phone?: string | null; requested_date?: string | null; message?: string | null; status?: string; created_at?: string }; Update: Partial<Database['public']['Tables']['viewing_requests']['Insert']> }
      profiles: { Row: { id: string; full_name: string | null; phone: string | null; role: string; notifications_seen_at: string | null; created_at: string; updated_at: string }; Insert: { id: string; full_name?: string | null; phone?: string | null; role?: string; notifications_seen_at?: string | null; created_at?: string; updated_at?: string }; Update: Partial<Database['public']['Tables']['profiles']['Insert']> }
      contacts: { Row: { id: string; owner_id: string | null; full_name: string; email: string | null; phone: string | null; contact_type: string; notes: string | null; created_at: string; updated_at: string }; Insert: { id?: string; owner_id?: string | null; full_name: string; email?: string | null; phone?: string | null; contact_type?: string; notes?: string | null; created_at?: string; updated_at?: string }; Update: Partial<Database['public']['Tables']['contacts']['Insert']> }
      leads: { Row: { id: string; contact_id: string; property_id: string | null; owner_id: string | null; status: string; priority: string; source: string; message: string | null; last_contacted_at: string | null; created_at: string; updated_at: string }; Insert: { id?: string; contact_id: string; property_id?: string | null; owner_id?: string | null; status?: string; priority?: string; source?: string; message?: string | null; last_contacted_at?: string | null; created_at?: string; updated_at?: string }; Update: Partial<Database['public']['Tables']['leads']['Insert']> }
      crm_tasks: { Row: { id: string; owner_id: string | null; assigned_to: string | null; title: string; description: string | null; due_date: string | null; status: string; priority: string; contact_id: string | null; lead_id: string | null; property_id: string | null; created_at: string; updated_at: string }; Insert: { id?: string; owner_id?: string | null; assigned_to?: string | null; title: string; description?: string | null; due_date?: string | null; status?: string; priority?: string; contact_id?: string | null; lead_id?: string | null; property_id?: string | null; created_at?: string; updated_at?: string }; Update: Partial<Database['public']['Tables']['crm_tasks']['Insert']> }
      visits: { Row: { id: string; owner_id: string | null; contact_id: string | null; lead_id: string | null; property_id: string; viewing_request_id: string | null; scheduled_at: string; status: string; notes: string | null; created_at: string; updated_at: string }; Insert: { id?: string; owner_id?: string | null; contact_id?: string | null; lead_id?: string | null; property_id: string; viewing_request_id?: string | null; scheduled_at: string; status?: string; notes?: string | null; created_at?: string; updated_at?: string }; Update: Partial<Database['public']['Tables']['visits']['Insert']> }
    }
  }
}
export type Tables<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Row']
export type TablesInsert<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Insert']
export type TablesUpdate<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Update']
